### ISSUE TITLE
Set Objectives

### ISSUE THREAD

**Issue by sharronrush** [w3c/wai-dynamic-planning#10]
Confusing: Identify and set measurable objectives that respond to identified accessibility problems.  

I don't think that objectives respond to accessibility problems. Are we trying to say to create measurable objectives that reflect the reality of the project goals and organizational structure...or what?

This whole first paragraph is confusing and has mixed tenses, etc. Needs a good rewrite. Suggest that examples include ways to integrate accessibility objectives into overall production and QA life cycle.

**Comment by iadawn** [comment]
I have taken a stab at preparing something in response to your comment. Any comments on it welcome.
