### ISSUE TITLE
Initiate overview page: Suggested edits for activity descriptions

### ISSUE THREAD

**Issue by susanatx** [w3c/wai-dynamic-planning#13]
Edits for clarity and more engaging language:
- Review the Situation (see my previous issue re: "assess" instead of "review")
  Know the organization's current state of accessibility to help determine scope of work ahead.
- Raise Awareness
  Communicate the aims, value-adds, and importance of accessibility across roles and teams.
- Develop business case
  A strong business case helps gain buy-in from stakeholders and can make accessibility an organizational priority
- Gather support 
  Organization-wide support is vital to ensure accessibility is sustained and distributed across roles.
- Set Objectives
  Clear objectives identify key deliverables, establish a timeline, and define how to measure success.

**Comment by iadawn** [comment]
I have incorporated most of the suggestions some with slight tweaks. Please do and any additional thoughts on the changes in 626d2b0
