### ISSUE TITLE
Text edits for Initiate Section

### ISSUE THREAD

**Issue by James-Green** [w3c/wai-dynamic-planning#17]
Here are a few minor edits to consider.  

**Initiate Page**
- develop clear, ~~measurably~~ measurable goals.
- will help **with** understanding the scale
- Clear, achievable objectives **define** ~~identify~~ what needs to be done, how to do it, and **metrics for** knowing when it is done.

**Learn the Basics**
- The **better** ~~more~~ you understand accessibility

**Assess the Current Situation**
- Web content policies and processes, ~~for example~~ **such as those related to** editing and publishing

**Set objectives**
- Objectives will help to focus your team, clarify what activities need to be planned, **define** ~~defines~~ what deliverables are required and when, and **ensure** ~~ensures~~ that successful delivery is easily determined.

**Comment by iadawn** [comment]
**Initiate Page**

Changes superceded by 626d2b0 and cdcf36a

**Set objectives**

Changes incorporated in b331047

**Others**

Included in ff3690f
