### ISSUE TITLE
Naming: this is not a "roadmap"

### ISSUE THREAD

**Issue by nitedog** [w3c/wai-dynamic-planning#2]
Judy raised the objection that this is not a "roadmap" and that the resource title is misleading. I agree with this comment now that I think of it from that perspective.

**Comment by iadawn** [comment]
Name has been changed to 'Planning and Managing Web Accessibility' following [EO Meeting on 4th Dec](http://www.w3.org/2015/12/04-eo-minutes.html#item01)
