### ISSUE TITLE
Last sentence in "Raise Awareness" first paragraph

### ISSUE THREAD

**Issue by hkramer** [w3c/wai-dynamic-planning#22]
Change "For example, marketing may benefit on more information to promote corporate social responsibility." to "For example, marketing may benefit by promoting corporate social responsibility."

**Comment by iadawn** [comment]
Definitely some words missing. I have changed to:

> For example, marketing may benefit from more information to help promote corporate social responsibility.

I think this makes more sense, considering the broader context. Feel free to comment if you feel it still needs to change.
