### ISSUE TITLE
"Explores factors important in developing a business case for accessibility."

### ISSUE THREAD

**Issue by hkramer** [w3c/wai-dynamic-planning#23]
Don't understand if the above text under "For more information" is supposed to be a link or relates to the link above it.

**Comment by iadawn** [comment]
This is intended to be text that describes the link above it. It may be that there is a need to consider how this is presented to make it clearer. I will raise in EO planning meeting and possibly bring for some discussion.

**Comment by iadawn** [comment]
Change style to more visibly connect the text to the link. Does this address your concern?
