### ISSUE TITLE
Planning Roadmap has too many words.

### ISSUE THREAD

**Issue by James-Green** [w3c/wai-dynamic-planning#3]
In reviewing the roadmap (btw I agree it's not a roadmap per #2) I was struck by the sheer number of words on the screen.  It's sooo many words, I'm concerned that we'll lose users if they have to concentrate that hard before they even get to a specific activity.  I suggest we reduce each activity down to about 2 words so they can be skimmed easily and on the sub-pages, give them icons as well. Below, you can see that I modified the activities under Initiate per my suggestion so you can compare their readability/skimmability to the other unmodified items.  Below that, you can see how my suggestion could further benefit skimming and choosing over the current wording on the sub-pages.

![screen shot 2015-11-04 at 8 29 35 pm](https://github-cloud.s3.amazonaws.com/assets%2F13589074%2F10958383%2Ff77917b2-8332-11e5-9230-8ab5889a5e49.png)

**Comment by iadawn** [comment]
Thanks for this. Agreed that there are too many words with nothing to grab and direct the reader. I like the approach that you have proposed. A plan for this morning was to consider how to cut down the length of the activity links... you have given me a head start.

Do you feel that the additional icons are an important component?

**Comment by James-Green** [comment]
I think they're _valuable_ if chosen carefully (e.g., the icon next to get support implies organizational type support) but I'm not sure how _important_.  I'm very visual so I tend to attach meaning to them as I skim the first time and navigate by them more than the words.  But, I'd love to hear what others think...

**Comment by bakkenb** [comment]
I agree with @James-Green opinion about the icons. To me they are attention grabbing as well. I realize it may be a huge challenge to come up with an icon for every activity in the planning tool. We could give it a shot if others like it.

**Comment by iadawn** [comment]
Activity icons were considered and felt to add too much clutter to the page ([EO Meeting 20 Nov 2015](http://www.w3.org/2015/11/20-eo-minutes.html#item05))
