### ISSUE TITLE
Plan Section Thorough Review Edits

### ISSUE THREAD

**Issue by James-Green** [w3c/wai-dynamic-planning#32]
http://w3c.github.io/wai-dynamic-planning/plan/
- Ensure costs are clarified and budget is secured for accessibility ~~activities, such~~ **activities such** as reviews, training, audits, and testing with users.
- On all sub-pages, remove the "For more information" and "Related activities" H3's if there is no content under them.

http://w3c.github.io/wai-dynamic-planning/plan/create_accessibility_policy.html
- Policies vary across organizations but ~~as~~ **at** a minimum would indicate what web accessibility standard you aim to conform with and by when. 
- Backing will ~~halp~~ **help** all implementation activities

http://w3c.github.io/wai-dynamic-planning/plan/assign_responsibilities.html
- Responsibilities can be spread throughout your organization, ~~which increases awareness and reduces the~~ **increasing awareness and reducing** risk of the activities overwhelming an individual or team. 
- Some example responsibilities ~~include;~~ **include:**

http://w3c.github.io/wai-dynamic-planning/plan/review_environment.html
- shared templates and coding ~~librariers,~~ **libraries,**

http://w3c.github.io/wai-dynamic-planning/plan/establish_monitoring_framework.html
- Some example criteria ~~include,~~ **include:**

http://w3c.github.io/wai-dynamic-planning/plan/engage_with_stakeholders.html
- set expectations and increase internal ~~commitment~~ **commitment** for accessibility.

**Comment by iadawn** [comment]
Thanks. All have been implemented except removing the empty 'Form more information' and 'Related activities'. These sections need another pass to populate so it is not clear which will be required. When they go live any empty ones will not appear on the page.
