### ISSUE TITLE
Layout of Planning Roadmap home page

### ISSUE THREAD

**Issue by happywebdiva** [w3c/wai-dynamic-planning#4]
As we discussed at the meeting Friday, the current layout (http://w3c.github.io/wai-dynamic-planning/) disorients me.  To me it looks like two columns, so the way I read it Implement follows Initiate instead of Plan.  I think aligning Implement with Monitor would fix this issue.

BTW, please ignore this if it's already (as I suspect) in the works.  I'm just following directions in "Work for this week."

**Comment by bakkenb** [comment]
I agree with @happywebdiva (Anna Belle) about the alignment of the four categories. I know that we have talked extensively about whether or not this is a linear process or if people will drop in on the category that they need to address at any given moment. But to help those that may want to use it in its entirety, then I think that the alignment needs to be adjusted so that it is intuitive as to what order would make sense to progress through this planning tool.

**Comment by James-Green** [comment]
I know the preference is not to number the 4 groups, so how about we add a breakpoint that would allow us to either show it vertically or horizontally, as one column or one row.  Then the confusion should be gone.  

The first example in this screenshot shows how it is now - under about 680px wide, you get one column of groups (which doesn't confuse anyone) with nav at the top (basically phone view) and greater than that width you get the 4 groups in 2-column layout (order of groups is now ambiguous).

Now look at the lower example - What if we added a 2nd breakpoint that kept the 1 column of groups, but with nav on the left.  That buys us a couple hundred pixels from the nav before the container of the content starts to get wider.  If we can just stretch it a couple hundred more pixels, to just over 1000 total, we could easily fit four columns when wider than the 2nd breakpoint, now that the links have been shortened....  
![screen shot 2015-11-19 at 6 46 26 pm](https://cloud.githubusercontent.com/assets/13589074/11288998/21f5912a-8eee-11e5-9f84-b9aa199ec486.png)

**Comment by iadawn** [comment]
There are now 4 layouts:
1. Narrow viewport: Single column activities with stacked primary navigation
2. Medium viewport: Single column activities with left hand primary navigation
3. Big viewport: Two column activities with a left hand primary navigation
4. Large viewport: Four column activities with a left hand primary navigation

WIth the initial change in how the activities lined up for the two column display, this should hopefully address the concerns.

Closed issue, please reopen if there are still concerns.
