### ISSUE TITLE
[Plan] Overview page edits

### ISSUE THREAD

**Issue by susanatx** [w3c/wai-dynamic-planning#40]
This is a comment related to the page [Plan](//w3c.github.io/wai-dynamic-planning/plan/)

**Opening paragraph**
current "Careful planning of the necessary efforts is critical to effective implementation later on. It ensures clear assessment of the required work, distribution of the tasks, and continual follow-up on progress."

Suggested "Careful planning is critical to effective implementation of any accessibility effort. It ensures a clear assessment of the required work, distribution of tasks, and continual follow-up on progress."

**Create a11y policy**
Current: "Document the goals, scope, and responsibilities important to accessibility." (This makes it sound like we're talking about a11y in general.)

Suggest: "Document the goals, scope, and responsibilities important to your organization." 

**Assign responsibilities**
Current: "Understand what roles need to be covered to help in creating the team and ensuring all tasks are covered."

Suggested: "Understand what roles are needed to ensure all tasks are covered." ("Team" seemed to come out of nowhere.)

**Review websites**
Current: "Before making changes, thoroughly review existing websites to identify issues to be fixed or avoided."

Suggested: "Identify issues to be fixed or avoided in existing websites." (Current sentence unnecessarily wordy.) 

**Review environment**
Current: "Technical and design resources will all directly impact on accessibility. Other factors, such as recruitment policies, will have an indirect impact."

Suggested: "Consider resources, processes, and tools in your organization that may impact accessibility efforts." (Changed for clarity and to add action verb at start of sentence.)

**Establish monitoring framework**
Current: "Create a standard way of monitoring and reporting findings, to help track and control progress."
Suggested: "Create a standard way of monitoring and reporting findings in order to track progress."

**Engage with Stakeholders**
Current: "Help maintain long-term support through regular communication with management and other stakeholders."

Suggested: "Maintain long-term support through regular communication with management and other stakeholders."

**Comment by iadawn** [comment]
Fixed by 098fbff
