### ISSUE TITLE
[Create accessibility policy] Suggested edits

### ISSUE THREAD

**Issue by susanatx** [w3c/wai-dynamic-planning#41]
This is a comment related to the page [Create accessibility policy](//w3c.github.io/wai-dynamic-planning/plan/create_accessibility_policy.html)

A web accessibility policy captures your goals and targets. Policies vary across organizations but at a minimum should establish the web accessibility standard you aim to conform with as well as a target date. For example, your policy might state that your website will meet all criteria in WCAG 2.0 Level AA within one year. A policy could also cover topics such as roles and responsibilities, content preparation processes, quality assurance, infrastructure, and reporting.

Ensure the policy has approval and backing from management. This will help all implementation activities, ensuring that resources are available and activities are prioritized.

**Comment by iadawn** [comment]
I have incorporated some of your suggested edits via e1ad626. If you are comfortable with my edits please feel free to close this issue.
