### ISSUE TITLE
[Track standards and legislation] Changes to standards

### ISSUE THREAD

**Issue by yatil** [w3c/wai-dynamic-planning#46]
This is a comment related to the page [Track standards and legislation](//w3c.github.io/wai-dynamic-planning/sustain/track_standards_and_legislation.html)

> Changes to standards are more likely to involve changes to design and coding approaches. As well as updating existing websites, review any existing common libraries, knowledge bases, and training material to ensure that the current standards are correctly reflected.

I have somehow an issue with that sentence. It sounds as if you have to redo everything once a standard is updated. I think with WCAG 2.0 extensions, for example, we try to be very backwards compatible so people don’t need to go back and redo everything. What about:

> Changes to standards might affect design and coding approaches as they might cover additional areas of accessibility. In certain cases this might necessitate updating existing websites, review any existing common libraries, knowledge bases, and training material to ensure that the current standards are correctly reflected.

**Comment by iadawn** [comment]
I have used a slight modification on your suggestion:

> Standards may change to cover additional areas of accessibility or respond to new technology. This might require new design and coding approaches for existing websites. Also review any existing common libraries, knowledge bases, and training material to ensure that the current standards are correctly reflected.

If you are ok with this, please feel free to close the issue.

**Comment by yatil** [comment]
I like the change, thank you! I think I would toss in “in certain situations” just to make clear that usually standards don’t force you to rewrite (large portions of) your site, but that’s just a personal preference and I don’t feel too strongly.
