### ISSUE TITLE
Visual columnar layout is misleading regarding order of the four groupings

### ISSUE THREAD

**Issue by davidberman** [w3c/wai-dynamic-planning#5]
Especially in the mid-width responsive design, I find it easy to mistake the sequence as Initiate-Implement-Plan-Monitor (even though the code order is correct). Aside from adjusting the layout, perhaps the four groupings should be numbered 1,2,3,4..

![image](https://cloud.githubusercontent.com/assets/1898660/11110179/e2a61c06-88c6-11e5-926d-43604c844e34.png)

**Comment by iadawn** [comment]
Related to #4

**Comment by iadawn** [comment]
Closed in favour of keeping discussion in #4
