### ISSUE TITLE
[Initiate] Change "Explore the situation"

### ISSUE THREAD

**Issue by sharronrush** [w3c/wai-dynamic-planning#61]
"situation" is the wrong word, suggest something like "environment" instead

**Comment by iadawn** [comment]
This activity seeks to be the quick initial check of accessibility in the organization. I wonder if 'Explore the environment', might also not hit the nail on the head in terms of title.

Possibly something like:

> Explore current status
> Explore current situation
> Where are you now
> Perform simple review

Sorry, but of a brain dump. I think the last one might be closer to what the activity is talking about. What do you think?

**Comment by bakkenb** [comment]
I agree with Sharron.

Just more ideas...
- Define current situation
- Review current situation
- Inventory current status

**Comment by sharronrush** [comment]
Understand the environment
Understand current status

I like an encompassing word like 'environment' to more clearly convey the need to understand more than just the legal framework or obligation. Environment asks you to consider corporate culture, how work is divided and compartmentalized, how change happens within the organization and other factors that will be important in the success of the effort.

**Comment by bakkenb** [comment]
Very good point. I like thinking more broadly like environment.

**Comment by iadawn** [comment]
I am suggesting:

> Explore the current environment

The aim is to be more encompasing, highlight that it is how things are now, and that this is not a review or evaluation. I have also made a slight change to the byline to highlight that the exploration includes considering obligations as well.

**Comment by iadawn** [comment]
@sharronrush, @bakkenb can you confirm that you are comfortable with the changes made and I will close this issue.

**Comment by bakkenb** [comment]
I agree with the changes and the current title "Explore the current environment."
