### ISSUE TITLE
Edit: intro Learn the Basics

### ISSUE THREAD

**Issue by sharronrush** [w3c/wai-dynamic-planning#7]
Omit passive voice:
"...the more effectively it can be implemented and promoted throughout your organization."

Suggested edit:
Accessibility integration often requires skilled advocacy in order to succeed. If you want to deepen your own understanding of web accessibility issues in order to be a more effective advocate, here are some suggested supporting resources:

**Comment by iadawn** [comment]
I wasn't sure about the first sentence in your suggested edit but the second is great. I have fused the original and your suggestion into:

> The more you understand accessibility, the more effectively it can be implemented and promoted in your organization. If you want to deepen your own understanding of web accessibility issues in order to be a more effective advocate, here are some suggested supporting activities: 

Is this ok?
