### ISSUE TITLE
[overall] design of sub-pages too spacey

### ISSUE THREAD

**Issue by shawna-slh** [w3c/wai-dynamic-planning#72]
On the sub-pages, e.g., [Plan](//w3c.github.io/wai-dynamic-planning/plan/index.html), I think the sentence under the h2 is way too big. Probably it should be the same size text as the main body text. It could have a different style, although I'm not sure that's needed.

Also, I think it would be easier to read when collapsed -- and more would fit above the fold -- if there was much less horizontal space. I suggest:
- tightening up the space between the h2 and the sentence after it, and
- less space before the h2s so they are tighter when collapsed -- then if needed, add a little space at the end of each section so when it's expanded, there's nice spacing before the next h2

**Comment by bakkenb** [comment]
+1 to all of comments by @slhenry
