### ISSUE TITLE
[plan] also consider resources

### ISSUE THREAD

**Issue by nitedog** [w3c/wai-dynamic-planning#75]
Think the resource needs a "determine resources", similar to "determine budget" - For example, I need the time of humans resources rather than direct monetary resources. I suggest the section should be expanded to "determine budget and resources", with the content adapted accordingly.

**Comment by iadawn** [comment]
I wonder how much that is a function of planning for accessibility or simply of planning in general?
What is particular about determining resources for accessibility?

**Comment by nitedog** [comment]
Same as for budget. Instead of identifying to "need X€ or X$", you could identify to "need the time of developer X, QA tester Y, or manager Z" to address accessibility issues. Without the time of these human resources you will not be able to implement accessibility. And money won't help either...

**Comment by iadawn** [comment]
A reader may not know what activities to consider from a budgetory perspective. Once thinking about them, the resources fall out of the budget as that is going to be the principal cost. In that case it is an implicit aspect of that activity. It may be worth making it explicity, but I think going down the route of specifying what will be needed may be too much. That is, I think avoiding explicitly pulling out roles would avoid being backed into a particular approach.

**Comment by nitedog** [comment]
Don't need to pull out specific roles. Making the implicit assumption more explicit - to also consider non-monetary resources - would be helpful, I think.

**Comment by iadawn** [comment]
Made some slight changes in ad78021 for your thoughts

**Comment by nitedog** [comment]
Thanks
