### ISSUE TITLE
Learn the Basics: suggested added activity

### ISSUE THREAD

**Issue by sharronrush** [w3c/wai-dynamic-planning#8]
Under Activity suggest to add an activity called "AT demonstrations" that invites staff with disabilities or community members with disabilities to attend a brown bag lunch or other informal demonstration where people can see accessibility at work, meet a person who relies on it, and asks questions, etc.

**Comment by bakkenb** [comment]
I like this idea. This has worked well in Pearson when we brought in people that matched the various personas that we were trying to develop for. When the product developers met these people they immediately wanted to solve the problems that they were faced with when trying to access the product or content that the developers where creating.

**Comment by iadawn** [comment]
I have included this as an item that readers might consider:

> - Set up assistive technology demonstrations.

Does this need more?
