### ISSUE TITLE
[Plan] Change Activity Order

### ISSUE THREAD

**Issue by bakkenb** [w3c/wai-dynamic-planning#82]
[strong] - <b>prior to publishing</b>

In the <a href=http://w3c.github.io/wai-dynamic-planning/plan/">Plan</a> stage of the resource, I think we need to switch the order of the two following activities:
- Review websites
- Review environment

I think organizations should review their environment and take stock in their resources, processes, and tools that will effect accessibility work, before they start the work on reviewing websites.

**Comment by iadawn** [comment]
There is nothing in either that would require them to be in the current order. There is also nothing that dictates that these activities should be done in a particular order (there are activities that it would make more sense to do before others but if a reader needs to approach them in a different way, that is fine).

Given the above I see no problem in swapping the order.
