### ISSUE TITLE
[Plan] - budget and resources

### ISSUE THREAD

**Issue by AndrewArch** [w3c/wai-dynamic-planning#83]
This is a comment related to the page [Plan](//w3c.github.io/wai-dynamic-planning/plan/index.html)

"... you should ensure that the presentation of budget is supported by ..." reads strangely to me, but I have no rewording suggestion at this stage. (or does it really mean the '... you should ensure that the _final budget_ is supported by ...'?)

**Comment by iadawn** [comment]
Hmm, yes, it does read a little bit peculiarly. I have made some tweaks to the activity (52b8c72). Hopefully this addresses your concerns.
