### ISSUE TITLE
[Plan] - review websites

### ISSUE THREAD

**Issue by AndrewArch** [w3c/wai-dynamic-planning#84]
This is a comment related to the page [Plan](//w3c.github.io/wai-dynamic-planning/plan/index.html)

Opening para refers to 'existing websites', but para 3 talks about accessibility during the development process. I'm ok with this, but flagging as an inconsistency.

**Comment by iadawn** [comment]
This was discussed in the chairs meeting and not felt to be a problem. The content reinforces the opportunity to integrate website review into subsequent planning activities. Which is a good thing.

As long as you are happy, keeping this as is, I am happy :)
