### ISSUE TITLE
Gather support

### ISSUE THREAD

**Issue by sharronrush** [w3c/wai-dynamic-planning#9]
Awkward sentence: "Other project teams involved in the creation of websites are another source of support. "

Suggest: Support for accessibility is often found among other project teams involved in the creation of websites - particularly if they are skilled in modern, responsive design theory.

**Comment by iadawn** [comment]
I have included the first part of the sentence. I think the second might be too limited as there are many aspects that other teams might be able to add value with.

Hope this is ok?
