### ISSUE TITLE
[Sustain] - adapt to new technologies

### ISSUE THREAD

**Issue by AndrewArch** [w3c/wai-dynamic-planning#90]
This is a comment related to the page [Sustain](//w3c.github.io/wai-dynamic-planning/sustain/index.html)

Under 'adapt to new technologies' / 'baseline support' - presume we still don't reference external resources such as ([www.html5accessibility.com/](http://www.html5accessibility.com/))?

**Comment by iadawn** [comment]
EO has a general policy of having a very high threshold of pointing to external resources. For this resource there hasn't been the desire/need to link to external resources.
