### ISSUE TITLE
Relation to other WAI resources

### ISSUE THREAD

**Issue by yatil** [w3c/wai-dynamic-planning#93]
- [Evaluation Approaches for Specific Contexts](https://www.w3.org/WAI/eval/considerations.html)
- [DRAFT Selecting Web Accessibility Evaluation Tools](https://www.w3.org/WAI/eval/selectingtools.html)
- [Using Combined Expertise to Evaluate Web Accessibility](https://www.w3.org/WAI/eval/reviewteams.html)

**Comment by nitedog** [comment]
Not sure about the context/question of this issue. Links to "specific contexts" and "combined expertise" are not in the latest draft. Please re-open as needed.

**Comment by yatil** [comment]
I don’t know anymore either, sorry for not giving more context.
